apiVersion: v1
name: zookeeper-operator
description: Zookeeper Operator Helm chart for Kubernetes
version: 0.2.8
appVersion: 0.2.8
keywords:
- zookeeper
- storage
home: https://github.com/pravega/zookeeper-operator
icon: https://zookeeper.apache.org/images/zookeeper_small.gif
